site_name: "BoI: Lua API Docs"
nav:
    - Home: index.md
    - Docs:
        - Home: index.md
        - "Last visited":
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
            - "": PLACEHOLDER.md
        - "Frequently used":
            - "Isaac": Isaac.md
            - "Entity": Entity.md
            - "EntityPlayer": EntityPlayer.md
            - "EntityNPC": EntityNPC.md
            - "EntityEffect": EntityEffect.md
            - "Game": Game.md
            - "Room": Room.md
            - "Level": Level.md
            - "ModCallbacks": enums/ModCallbacks.md
        - "Enums":
            - "ActionTriggers": enums/ActionTriggers.md
            - "ActiveSlot": enums/ActiveSlot.md
            - "BabySubType": enums/BabySubType.md
            - "BackdropType": enums/BackdropType.md
            - "BatterySubType": enums/BatterySubType.md
            - "BedSubType": enums/BedSubType.md
            - "BombSubType": enums/BombSubType.md
            - "BombVariant": enums/BombVariant.md
            - "ButtonAction": enums/ButtonAction.md
            - "CacheFlag": enums/CacheFlag.md
            - "CallbackPriority": enums/CallbackPriority.md
            - "Card": enums/Card.md
            - "Challenge": enums/Challenge.md
            - "ChampionColor": enums/ChampionColor.md
            - "ChestSubType": enums/ChestSubType.md
            - "CoinSubType": enums/CoinSubType.md
            - "CollectibleType": enums/CollectibleType.md
            - "DamageFlag": enums/DamageFlag.md
            - "Difficulty": enums/Difficulty.md
            - "Direction": enums/Direction.md
            - "DoorSlot": enums/DoorSlot.md
            - "DoorState": enums/DoorState.md
            - "DoorVariant": enums/DoorVariant.md
            - "DrawStringAlignment": enums/DrawStringAlignment.md
            - "EffectVariant": enums/EffectVariant.md
            - "EntityCollisionClass": enums/EntityCollisionClass.md
            - "EntityFlag": enums/EntityFlag.md
            - "EntityGridCollisionClass": enums/EntityGridCollisionClass.md
            - "EntityPartition": enums/EntityPartition.md
            - "EntityType": enums/EntityType.md
            - "FamiliarVariant": enums/FamiliarVariant.md
            - "GameStateFlag": enums/GameStateFlag.md
            - "GridCollisionClass": enums/GridCollisionClass.md
            - "GridEntityType": enums/GridEntityType.md
            - "GridRooms": enums/GridRooms.md
            - "HeartSubType": enums/HeartSubType.md
            - "InputHook": enums/InputHook.md
            - "ItemConfig": enums/ItemConfig.md
            - "ItemPoolType": enums/ItemPoolType.md
            - "ItemType": enums/ItemType.md
            - "Keyboard": enums/Keyboard.md
            - "KeySubType": enums/KeySubType.md
            - "LaserOffset": enums/LaserOffset.md
            - "LaserSubType": enums/LaserSubType.md
            - "LaserVariant": enums/LaserVariant.md
            - "LevelCurse": enums/LevelCurse.md
            - "LevelStage": enums/LevelStage.md
            - "LevelStateFlag": enums/LevelStateFlag.md
            - "LocustSubtypes": enums/LocustSubtypes.md
            - "ModCallbacks": enums/ModCallbacks.md
            - "Mouse": enums/Mouse.md
            - "Music": enums/Music.md
            - "NpcState": enums/NpcState.md
            - "NullItemID": enums/NullItemID.md
            - "PickupPrice": enums/PickupPrice.md
            - "PickupVariant": enums/PickupVariant.md
            - "PillColor": enums/PillColor.md
            - "PillEffect": enums/PillEffect.md
            - "PlayerForm": enums/PlayerForm.md
            - "PlayerSpriteLayer": enums/PlayerSpriteLayer.md
            - "PlayerType": enums/PlayerType.md
            - "PoopPickupSubType": enums/PoopPickupSubType.md
            - "PoopSpellType": enums/PoopSpellType.md
            - "ProjectileFlags": enums/ProjectileFlags.md
            - "ProjectileVariant": enums/ProjectileVariant.md
            - "RenderMode": enums/RenderMode.md
            - "RoomDescriptor": enums/RoomDescriptor.md
            - "RoomShape": enums/RoomShape.md
            - "RoomTransitionAnim": enums/RoomTransitionAnim.md
            - "RoomType": enums/RoomType.md
            - "SackSubType": enums/SackSubType.md
            - "SeedEffect": enums/SeedEffect.md
            - "SkinColor": enums/SkinColor.md
            - "SortingLayer": enums/SortingLayer.md
            - "SoundEffect": enums/SoundEffect.md
            - "StageType": enums/StageType.md
            - "TearFlags": enums/TearFlags.md
            - "TearVariant": enums/TearVariant.md
            - "TrinketType": enums/TrinketType.md
            - "UseFlag": enums/UseFlag.md
            - "WeaponType": enums/WeaponType.md
        - "Globals": Globals.md
        - "Global Functions": GlobalFunctions.md
        - "BitSet128": BitSet128.md
        - "Color": Color.md
        - "CppContainer":
            - "ArrayProxy":
                - "RoomConfigEntries": CppContainer_ArrayProxy_RoomConfigEntries.md
                - "RoomConfigSpawns": CppContainer_ArrayProxy_RoomConfigSpawns.md
                - "RoomDescriptor": CppContainer_ArrayProxy_RoomDescriptor.md
                - "intValues": CppContainer_ArrayProxy_intValues.md
            - "EntityList": CppContainer_EntityList.md
            - "Vector":
                - "CardConfigList": CppContainer_Vector_CardConfigList.md
                - "CostumeConfigList": CppContainer_Vector_CostumeConfigList.md
                - "EffectList": CppContainer_Vector_EffectList.md
                - "ItemConfigList": CppContainer_Vector_ItemConfigList.md
                - "PillConfigList": CppContainer_Vector_PillConfigList.md
                - "VectorList": CppContainer_Vector_VectorList.md
        - "Entity":
            - "Entity": Entity.md
            - "EntityBomb": EntityBomb.md
            - "EntityEffect": EntityEffect.md
            - "EntityFamiliar": EntityFamiliar.md
            - "EntityKnife": EntityKnife.md
            - "EntityLaser": EntityLaser.md
            - "EntityNPC": EntityNPC.md
            - "EntityPickup": EntityPickup.md
            - "EntityPlayer": EntityPlayer.md
            - "EntityProjectile": EntityProjectile.md
            - "EntityTear": EntityTear.md
        - "EntityPtr": EntityPtr.md
        - "EntityRef": EntityRef.md
        - "Font": Font.md
        - "FontRenderSettings": FontRenderSettings.md
        - "Game": Game.md
        - "GridEntity":
            - "GridEntity": GridEntity.md
            - "GridEntityDoor": GridEntityDoor.md
            - "GridEntityPit": GridEntityPit.md
            - "GridEntityPoop": GridEntityPoop.md
            - "GridEntityPressurePlate": GridEntityPressurePlate.md
            - "GridEntityRock": GridEntityRock.md
            - "GridEntitySpikes": GridEntitySpikes.md
            - "GridEntityTNT": GridEntityTNT.md
        - "GridEntityDesc": GridEntityDesc.md
        - "HUD": HUD.md
        - "ItemConfig":
            - "ItemConfig Functions": ItemConfig.md
            - "ItemConfig - Card": ItemConfig_Card.md
            - "ItemConfig - Costume": ItemConfig_Costume.md
            - "ItemConfig - Item": ItemConfig_Item.md
            - "ItemConfig - PillEffect": ItemConfig_PillEffect.md
        - "Input": Input.md
        - "Isaac": Isaac.md
        - "ItemPool": ItemPool.md
        - "KColor": KColor.md
        - "Level": Level.md
        - "MusicManager": MusicManager.md
        - "Mod Reference": ModReference.md
        - "Options": Options.md
        - "PathFinder": PathFinder.md
        - "PlayerTypes":
            - "PlayerTypesActiveItemDesc": PlayerTypes_ActiveItemDesc.md
            - "PlayerTypesPosVel": PlayerTypes_PosVel.md
        - "ProjectileParams": ProjectileParams.md
        - "QueueItemData": QueueItemData.md
        - "Room": Room.md
        - "RoomConfig":
            - "Entry": RoomConfig_Entry.md
            - "Room": RoomConfig_Room.md
            - "Spawn": RoomConfig_Spawn.md
        - "RoomDescriptor": RoomDescriptor.md
        - "RNG": RNG.md
        - "Seeds": Seeds.md
        - "Sprite": Sprite.md
        - "SFXManager": SFXManager.md
        - "TearParams": TearParams.md
        - "TemporaryEffect": TemporaryEffect.md
        - "TemporaryEffects": TemporaryEffects.md
        - "Vector": Vector.md
    - Entities:
        - "Overview": entities/Overview.md
        - "Boss Data":
          - "Chapter 1": entities/bosses/Chapter1.md
          - "Chapter 1.5": entities/bosses/Chapter1-5.md
          - "Chapter 2": entities/bosses/Chapter2.md
          - "Chapter 2.5": entities/bosses/Chapter2-5.md
          - "Chapter 3": entities/bosses/Chapter3.md
          - "Chapter 3.5": entities/bosses/Chapter3-5.md
          - "Chapter 4": entities/bosses/Chapter4.md
          - "Chapter 4.5": entities/bosses/Chapter4-5.md
          - "Final Bosses": entities/bosses/FinalBosses.md
        - "Entity Data": entities/EntityData.md
        - "Fissure Spawner": entities/FissureSpawner.md
        - "Ball & Chain": entities/SpikeBallChain.md
    - Tutorials:
        - "Example Project": tutorials/ExampleProject.md
        - "Functions in Lua": tutorials/FunctionsInLua.md
        - "Good Coding Practices": tutorials/GoodPractices.md
        - "Getting Coding Help": tutorials/GettingHelp.md
        - "Math and Lua Tips": tutorials/MathAndLuaTips.md
        - "Adding Costumes to items without LUA": tutorials/AddingCostumesWithoutLUA.md
        - "Debugging with ZeroBrane Studio": tutorials/ZeroBraneStudio.md
        - "Debug Console": tutorials/DebugConsole.md
        - "Using additional .lua Files": tutorials/Using-Additional-Lua-Files.md
        - "Using the standard library": tutorials/Standard-Library.md
        - "Writing screen shaders": tutorials/Writingscreenshaders.md
        - "Render text": tutorials/Tutorial-Rendertext.md
        - "Directories and save files": tutorials/directories-and-save-files.md
        - "Mod Organization": "tutorials/mod-organization.md"
        - "Storing Data": "tutorials/storing-data.md"
        - "Custom Callbacks": tutorials/CustomCallbacks.md
    - XMLs:
        - "XML Overview": xml/XMLFiledocumentation.md
        - "achievements.xml" : xml/achievements.md
        - "ambush.xml" : xml/ambush.md
        - "babies.xml" : xml/babies.md
        - "bombcostumes.xml" : xml/bombcostumes.md
        - "backdrops.xml" : xml/backdrops.md
        - "bosscolors.xml" : xml/bosscolors.md
        - "bossoverlays.xml" : xml/bossoverlays.md
        - "bosspools.xml" : xml/bosspools.md
        - "bossportraits.xml" : xml/bossportraits.md
        - "challenges.xml" : xml/challenges.md
        - "costumes2.xml" : xml/costumes2.md
        - "curses.xml" : xml/curses.md
        - "cutscenes.xml" : xml/cutscenes.md
        - "entities2.xml" : xml/entities2.md
        - "fortunes.txt" : xml/fortunes.md
        - "fxlayers.xml" : xml/fxlayers.md
        - "giantbook.xml" : xml/giantbook.md
        - "itempools.xml" : xml/itempools.md
        - "items.xml" : xml/items.md
        - "items_metadata.xml" : xml/items_metadata.md
        - "locusts.xml" : xml/locusts.md
        - "minibosses.xml" : xml/minibosses.md
        - "music.xml" : xml/music.md
        - "nightmares.xml" : xml/nightmares.md
        - "players.xml" : xml/players.md
        - "playerforms.xml" : xml/playerforms.md
        - "pocketitems.xml" : xml/pocketitems.md
        - "preload.xml" : xml/preload.md
        - "recipes.xml" : xml/recipes.md
        - "rules.txt" : xml/rules.md
        - "seedmenu.xml" : xml/seedmenu.md
        - "seeds.txt" : xml/seeds.md
        - "sounds.xml" : xml/sounds.md
        - "stages.xml" : xml/stages.md
        - "translations.xml" : xml/translations.md
        - "wisps.xml" : xml/wisps.md
    - FAQ:
        - "FAQ" : faq/FaqHome.md
        - "Interactive FAQ" : faq/interactive_FAQ.md
        - "Basic Information" : faq/BasicInformation.md
        - "Getting Started" : faq/GettingStarted.md
        - "Coding Help" : faq/Coding.md
        - "Lua Language" : faq/Lua.md
        - "Troubleshooting" : faq/Troubleshoot.md
        - "Launch Options": faq/LaunchOptions.md
    - Tools:
        - "Tools Overview" : tutorials/Tools.md
        - "XML Validator" : tutorials/Tool_XMLValidator.md
        - "Animation Editor" : tutorials/Tool_AnimationEditor.md
        - "Itempool Editor" : tutorials/Tool_ItemPoolEditor.md
    - Bugs: https://github.com/Meowlala/RepentanceAPIIssueTracker
    - Tags: tags.md
    - Lua 5.3 Docs: https://www.lua.org/manual/5.3/
theme:
    name: material
    custom_dir: overrides
    features:
        - search.suggest
        - search.highlight
        - search.share
        - navigation.tabs
        - navigation.instant
        - navigation.top
    icon:
        repo: fontawesome/brands/github
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: amber
          accent: amber
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
plugins:
  - search:
      separator: '[\s\-\.\_\·]+'
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
  - tags:
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wofsauge/IsaacDocs
      name: "BoI: Lua API Docs on GitHub"
    - icon: fontawesome/brands/discord
      link: https://discord.gg/isaac
      name: "Official Discord Server"
  version:
    provider: mike
    default: rep
  analytics:
    provider: google
    property: G-ZBKP3LLT96
extra_css:
    - css/custom.css
extra_javascript:
    - https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - js/tablesort.number.min.js
    - js/customJS.js
    - js/jquery.mark.min.js
copyright: "Copyright &copy; 2021 - 2025 Wofsauge (Discord: Wofsauge#6503)"
repo_url: https://github.com/wofsauge/IsaacDocs
repo_name: wofsauge/IsaacDocs
edit_uri: edit/main/docs/
site_url: ""
use_directory_urls: False
